name: 🏷️ Pre-Release Modules

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  check:
    name: 🔍 Check Release Necessity
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    outputs:
      release_tag: ${{ steps.check.outputs.release_tag }}
      release_name: ${{ steps.check.outputs.release_name }}
      version_exists: ${{ steps.check.outputs.version_exists }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Fetch All Tags
        run: git fetch --tags
      - name: Check Versions
        id: check
        run: |
          VERSION=$(python -c "from bookshelf import version; print(version())")
          MC_VERSIONS=$(python -c "from bookshelf import mc_versions; print(mc_versions())")

          mc_versions=$(echo $MC_VERSIONS | sed 's/ /,/g')
          echo "release_tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "release_name=v$VERSION - MC $mc_versions" >> $GITHUB_OUTPUT

          if [ -n "$(git tag -l "v$VERSION")" ]; then
            echo "version_exists=true" >> $GITHUB_OUTPUT
          else
            echo "version_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Debug Outputs
        run: |
          echo "release_tag=${{ steps.check.outputs.release_tag }}"
          echo "release_name=${{ steps.check.outputs.release_name }}"
          echo "version_exists=${{ steps.check.outputs.version_exists }}"

  release:
    name: 📦 Create Pre-Release
    needs: check
    if: ${{ needs.check.outputs.version_exists == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Git User
        uses: fregante/setup-git-user@v2
      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Install Dependencies
        run: pdm install
      - name: Build Release Files
        run: pdm run modules release
      - uses: softprops/action-gh-release@v2
        with:
          body_path: docs/_templates/changelog/${{ needs.check.outputs.release_tag }}.md
          name: ${{ needs.check.outputs.release_name }}
          tag_name: dev
          prerelease: true
          files: release/*.zip
