name: 🔖 Upload build assets

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup environment variables
        run: |
          pip install -r scripts/requirements.txt
          python3 scripts/definitions.py
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

  package:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Package datapacks
        run: python3 scripts/distribute.py -v ${{ env.MC_VERSION }}-${{ env.VERSION }} -w 0
      - name: Package world
        uses: aksiome/minecraft-package@master
        with:
          config: .mcwpack.yml
          source: ${{ env.WORLD_PATH }}
          target: ${{ env.BUILD_PATH }}/bookshelf-world-${{ env.MC_VERSION }}-${{ env.VERSION }}.zip

  upload:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.BUILD_PATH }}/*.zip

  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update latest tag
        uses: EndBug/latest-tag@latest
